--liquibase formatted sql
--changeSet mikeo:createcontractors-101
CREATE TABLE public.contractors (contractor_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(45) NOT NULL, last_name VARCHAR(45) NOT NULL, email VARCHAR(50), active BOOLEAN DEFAULT TRUE NOT NULL, username VARCHAR(16) NOT NULL, CONSTRAINT contractor_pkey PRIMARY KEY (contractor_id));
--rollback drop table contractors

--changeSet mikeo:insertintocontractors-102
INSERT INTO public.contractors (contractor_id, first_name, last_name, email, active, username) VALUES 
  (1, 'Max', 'Junior', 'Max.Junior@example.com', TRUE, 'Max'),
  (2, 'Stephanie', 'James', 'Steph.James@outsourcingex.com', TRUE, 'Steph');
--rollback delete from contractors where contractor_id = 1
--rollback delete from contractors where contractor_id = 2